GET http://localhost:3000/api/redirects

### 

GET http://localhost:3000/api/redirects/677009d9fc8d5b7c5950ac2b

### 

POST http://localhost:3000/api/redirects
Content-Type: application/json

{
  "action": "createRedirect",
  "sourceUrl": "/as",
  "destinationUrl": "/sa",
  "httpStatusCode": "301"
}

### 

PUT http://localhost:3000/api/redirects/679c74143bc7590364069e68
Content-Type: application/json

{
  "sourceUrl": "/Home"
}
### 

DELETE http://localhost:3000/api/redirects/679bdced7e97fc98a6574307
Content-Type: application/json

{
"_id": "679c74143bc7590364069e68"
}

// User test

GET http://localhost:3000/api/users
###

GET http://localhost:3000/api/users/677006fffc8d5b7c5950ac28
###

POST http://localhost:3000/api/users
Content-Type: application/json

{
  "action": "register",
  "email": "Anton@mail.com",
  "password": "anton",
  "fullName": "anton testsson"
}

# {
#   "action": "login",
#   "email": "Anton@mail.com",
#   "password": "anton"
# }
###
// Måste göras
DELETE http://localhost:3000/api/users/Lägg-till-id:nr
Content-Type: application/json

{
"_id": "Lägg till id:nr"
}
###

PUT http://localhost:3000/api/users/Lägg-till-id:nr
Content-Type: application/json

{
"email": "janedoe@example.com", "password": "hashedpassword456"
}